<a href="https://colab.research.google.com/github/dawidSkowron20/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.5'

In [4]:
print(dir(np))

In [ ]:
help(np.array) # w bibliotece numpy dane sa tego samego typu 

1D array

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [8]:
type(x)

numpy.ndarray

In [10]:
x.ndim # wymiar tablicy 

1

In [11]:
x.shape # kształt tablicy, 2 elementy w jednowymiarowej tablicy

(2,)

In [12]:
x.size

2

In [13]:
x.dtype # typ danych w tablicy 

dtype('int64')

In [15]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [16]:
x.dtype

dtype('float64')

In [17]:
x.size

3

2D Array

In [19]:
x = np.array([[1, 2], [-3, 1]]) # odpowiednik macierzy 
x

array([[ 1,  2],
       [-3,  1]])

In [20]:
x.ndim

2

In [21]:
x.shape

(2, 2)

In [22]:
x = np.array([[1, 2, 3], [4, 2, 1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [23]:
x.shape

(2, 3)

In [24]:
x.size

6

3D Array

In [26]:
x = np.array(
    [[[3, 2, 1],
      [5, 2, 1]],
     
     [[4, 6, 2],
      [6, 3, 4]],
     
     [[2, 3, 2],
      [2, 1, 3]]]
     
     )
x

array([[[3, 2, 1],
        [5, 2, 1]],

       [[4, 6, 2],
        [6, 3, 4]],

       [[2, 3, 2],
        [2, 1, 3]]])

In [27]:
x.ndim

3

In [28]:
x.shape # 3 elementy po 2 kolumny po 3 wiersze

(3, 2, 3)