<a href="https://colab.research.google.com/github/dawidSkowron20/data-science-bootcamp/blob/main/wprowadzenie_numpy/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.__version__

'1.21.5'

In [ ]:
print(dir(np))

In [ ]:
help(np.array) # w bibliotece numpy dane sa tego samego typu 

1D array

In [ ]:
x = np.array([1, 3])
x

array([1, 3])

In [ ]:
print(x)

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndim # wymiar tablicy 

1

In [ ]:
x.shape # kształt tablicy, 2 elementy w jednowymiarowej tablicy

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype # typ danych w tablicy 

dtype('int64')

In [ ]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
x.size

3

2D Array

In [ ]:
x = np.array([[1, 2], [-3, 1]]) # odpowiednik macierzy 
x

array([[ 1,  2],
       [-3,  1]])

In [ ]:
x.ndim

2

In [ ]:
x.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 3], [4, 2, 1]])
print(x)

[[1 2 3]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x.size

6

3D Array

In [ ]:
x = np.array(
    [[[3, 2, 1],
      [5, 2, 1]],
     
     [[4, 6, 2],
      [6, 3, 4]],
     
     [[2, 3, 2],
      [2, 1, 3]]]
     
     )
x

array([[[3, 2, 1],
        [5, 2, 1]],

       [[4, 6, 2],
        [6, 3, 4]],

       [[2, 3, 2],
        [2, 1, 3]]])

In [ ]:
x.ndim

3

In [ ]:
x.shape # 3 elementy po 2 kolumny po 3 wiersze

(3, 2, 3)

Typy danych


In [ ]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [ ]:
A = np.array([1.0, 2.0, 3.0])
A.dtype

dtype('float64')

In [ ]:
A = np.array([1, 2, 3], dtype=float) # szybka zmiana na zmiennoprzeciwkowe
A.dtype

dtype('float64')

In [ ]:
A

array([1., 2., 3.])

In [ ]:
A = np.array([1, 2, 3], dtype='complex') # liczby urojone 
A.dtype

dtype('complex128')

In [ ]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
A = np.array([1.0, 2.3, 3.3], dtype='int') # utrata elementu danych, zwykła
                                          # konwersja
A

array([1, 2, 3])

In [ ]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [ ]:
A = np.array([24, 120 , 213], dtype=np.int8)
A.dtype

dtype('int8')

In [ ]:
A = np.array([24, 120 , 213], dtype=np.uint8)
A.dtype

dtype('uint8')

Tworzenie tablic

In [ ]:
np.zeros(shape = (4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(shape = (4, 10), dtype=int) # maska do algorytmow

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
np.ones(shape = (5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full(shape=(4, 5), fill_value=4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [ ]:
np.arange(10) # to samo co list(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(start=5, stop=10, step=2)

array([5, 7, 9])

In [ ]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
np.arange(start=100, stop=10, step=-10) # odwrotna kolejność

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [ ]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [ ]:
np.linspace(start=0, stop=1 , num=10) # dziesięc równo rozłożonych elementów 
                                      # z przedziału od 0 do 1 

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
A = np.arange(15)

In [ ]:
A.reshape((3, 5)) # zmienianie rozmiaru tablicy

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((3, -1)) # pajton sam dopiera nam rozmiar 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape((-1, 3)) # efekt na odwrót

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

Podstawowe operacje na tablicach

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B # rozmiar tablic muszą się zgadzać jak w macierzach

array([6, 0, 7, 4])

In [ ]:
A - B # odejmowanie tak samo 

array([0, 2, 1, 0])

In [ ]:
A * B # mnożenie natomiast element po elemencie, nie jak w macierzy

array([ 9, -1, 12,  4])

In [ ]:
A / B 

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
z = np.arange(1, 5)

In [ ]:
z.reshape(4, -1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
A

array([3, 1, 4, 2])

In [ ]:
A * z

array([ 3,  2, 12,  8])

In [ ]:
A + 3

array([6, 4, 7, 5])

In [ ]:
3 * A # mnożenie przez skalar

array([ 9,  3, 12,  6])

In [ ]:
A, B

(array([3, 1, 4, 2]), array([ 3, -1,  3,  2]))

In [ ]:
np.add(A, B)

array([6, 0, 7, 4])

In [ ]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
# Mnożenie macierzy
X = np.array([[1, 3], [-2, 0]]) 
Y = np.array([[6, 0], [-1, 2]])
print(X)
print()
print(Y)

[[ 1  3]
 [-2  0]]

[[ 6  0]
 [-1  2]]


In [ ]:
X * Y # nie jest to mnożenie macierzy

array([[6, 0],
       [2, 0]])

In [ ]:
np.dot(X, Y) # to już tak

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y) # alternatywa 

array([[  3,   6],
       [-12,   0]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn() # losowa wartosc z rozkladu normalnego

1.764052345967664

In [ ]:
np.random.randn(10) # 10 losowo wygenerowanych parametrów z rozkładu normalnego

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [ ]:
np.random.randn(10, 4) # 4 to liczba kolumn czy tez zmiennych a 10 to liczba wierszy 

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [ ]:
np.random.rand() # rozkład jednostajny na przedziale, przedział 0 - 1

0.1965823616800535

In [ ]:
np.random.rand(10) 

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [ ]:
np.random.rand(10, 2) 

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [ ]:
np.random.randint(10) # zwraca liczbe od 0 do 9

3

In [ ]:
np.random.randint(low=10, high=101) # generowanie liczby losowej z przedzialu od 10 do 100

56

In [ ]:
np.random.randint(low=10, high=101, size = 10) # size pozwoli wygenerować tyle
                                               # liczba ile potrzebujemy

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [ ]:
np.random.choice([4, 2, 1, 3]) # zwraca losowy element z listy

4

In [ ]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.random.shuffle(data)
data

array([1, 0, 5, 2, 9, 7, 4, 6, 8, 3])

In [ ]:
# ważny aspekt, w pandasie trzeba było przypisać do zmiennej wartość
# w numpy wystarczy wywołać funkcję

Podstawowe funkcje

In [2]:
np.exp(1) # stała eulera

2.718281828459045

In [4]:
np.sqrt(2)

1.4142135623730951

In [5]:
np.all([2, 3, 1]) # bada każdy element i sprawdza czy jest false czy true 

True

In [6]:
np.all([2, 0, 1])

False

In [11]:
np.any([0, 0 , 0])

False

In [14]:
A = np.random.rand(5)
A

array([0.33857697, 0.9984422 , 0.21500207, 0.94934594, 0.59461297])

In [15]:
np.argmax(A)

1

In [16]:
A[np.argmax(A)]

0.9984422035010057

In [17]:
np.argmin(A) # zwraca indeks 

2

In [18]:
A[np.argmin(A)]

0.2150020678449719

In [19]:
max(A) # adekwatne użycie

0.9984422035010057

In [29]:
np.argsort(A, axis=0) # rosnąco

array([2, 0, 4, 3, 1])

In [30]:
np.argsort(A, axis=0)[::-1] # malejąco

array([1, 3, 4, 0, 2])

Funkcje statystyczne

In [31]:
np.std(A) # odchylenie

0.31481764996534434

In [32]:
np.mean(A)

0.6191960317514236

In [33]:
np.median(A)

0.5946129727220052

Indeksowanie, wycinanie

In [35]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# szybkie przypomnienie
# A[idx], A[start:stop] , A[start:], A[:stop]


In [36]:
A[[0, 2]]

array([0, 2])

In [37]:
A[-1]

19

In [41]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
A[0] # wycinanie wierszy

array([0, 1, 2, 3, 4])

In [43]:
A[:, 2] # wycinanie trzeciej kolumny

array([ 2,  7, 12, 17])

In [44]:
A[1,1] # wycinanie konkretnego elementu

6

In [45]:
A[1,3]

8

In [47]:
A[1:3,1:4] # tak trzeba bo index stop jest otwarty 

array([[ 6,  7,  8],
       [11, 12, 13]])

In [49]:
A[1, 2] = 14 # zmiana elementow 
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [50]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [52]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [53]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [54]:
for item in A.flat:
  print(item) 

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [55]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
A.shape

(4, 5)

In [57]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [58]:
A.ravel() # wypłaszczenie danych

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [59]:
A.T # macierz transponowana

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [63]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [64]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [65]:
A[A > 0] # nakładanie maski 

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [69]:
try:
  A[A > -5 and A < 5] 
except ValueError: 
  print(np.bitwise_and(A > -5, A < 5)) # wniosek z tego jest taki że tylko
                                       # tak możemy nakładać maski z and np.

[[False False False False]
 [False False False False]
 [False False False  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]
 [False False False False]]


In [70]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [74]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])