<a href="https://colab.research.google.com/github/dawidSkowron20/data-science-bootcamp/blob/main/wprowadzenie_numpy/02_algebra_liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Norma wektora  i jego długość w R2

In [7]:
v1 = np.array([-1, 4])
v1

array([-1,  4])

In [8]:
np.linalg.norm(v1) # długośc wektora 

4.123105625617661

Norma euklidesowa w Rn

In [10]:
v2 = np.array([-10, 10, 13])
np.linalg.norm(v2) # długośc wektora w przestrzeni R3

19.209372712298546

Odległośc dwóch punktów w przestrzeni R2







In [13]:
p = np.array([3, 0])
q = np.array([0, 4])
np.linalg.norm(p-q)

5.0

Odległośc dwóch punktów w przestrzeni Rn


In [14]:
p = np.array([3, 0, 1])
q = np.array([0, 4, 2])
np.linalg.norm(p-q)

5.0990195135927845

Mnożenie macierzy

Przykład 





In [16]:
A = np.array([[5, 3], [3, 9]])
B = np.array([[1], [-1]])
print(A, '\n')
print(B)

[[5 3]
 [3 9]] 

[[ 1]
 [-1]]


In [17]:
Z = np.dot(A, B)
print(Z)

[[ 2]
 [-6]]


In [18]:
Z.shape

(2, 1)

In [21]:
try:
  D = np.dot(B, A)
except ValueError:
  print('Nie można tak zrobić ze względu na rozmiar macierzy'
          ' i warunek ich mnożenia.')

Nie można tak zrobić ze względu na rozmiar macierzy i warunek ich mnożenia.


Wyznacznik macierzy 2x2

In [22]:
A = np.array([[2, 4],
              [-1, 3]])
A

array([[2, 4],
       [1, 3]])

In [24]:
round(np.linalg.det(A))

2

Ślad macierzy
  - Suma elementów na przekątnej w macierzy kwadratowej

In [26]:
A = np.array([[2, 4],
              [-1, 3]]) # 2 + 3 = 5

np.trace(A)

5

Macierz jednostkowa

In [27]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [28]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Macierz odwrotna
AB = BA = I

In [29]:
A

array([[ 2,  4],
       [-1,  3]])

In [30]:
B = np.linalg.inv(A)
B # macierz odwrotna do A

array([[ 0.3, -0.4],
       [ 0.1,  0.2]])

In [32]:
np.set_printoptions(precision=4, suppress=True)
A @ B

array([[1., 0.],
       [0., 1.]])

In [33]:
B @ A # jest takie same jak A @ B czyli warunek spełniony

array([[ 1., -0.],
       [ 0.,  1.]])

Macierz transponowana

In [34]:
A

array([[ 2,  4],
       [-1,  3]])

In [35]:
A.T # krótszy zapis

array([[ 2, -1],
       [ 4,  3]])

In [37]:
np.transpose(A)

array([[ 2, -1],
       [ 4,  3]])

Rozwiązywanie układów równań

In [38]:
A = np.array([[2, 4], [1, -1]]) # macierz współczynników
B = np.array([[10], [-1]]) # macierz wyrazów wolnych
print(A, '\n')
print(B)

[[ 2  4]
 [ 1 -1]] 

[[10]
 [-1]]


In [41]:
A_inv = np.linalg.inv(A)
A_inv # 

array([[ 0.1667,  0.6667],
       [ 0.1667, -0.3333]])

In [42]:
X = np.dot(A_inv, B) # mnożymy macierz odwrotną z macierzą wyrazów wolnych  
X # wynik macierzy

array([[1.],
       [2.]])